import highscore from './../img/estrella-con-relleno.png';
import lowscore from './../img/estrella-sin-relleno.png';
import BICHON from './../img/maltesToy.png';
import SCHNAUZER from  './../img/Schnauzer.png';
export const PET_BICHON    = BICHON;
export const PET_SCHNAUZER = SCHNAUZER;
export const CHARACT2 = "Ladrador";
export const CHARACT1 = "Vitalidad";
export const CHARACT3 = "Instinto de vigilancia";
export const CHARACT4 = "Instinto de protección";
export const CHARACT5 = "Relación con niños";
export const CHARACT6 = "Relación con perros";
export const CHARACT7 = "Capacidad de aprendizaje";
export const CHARACT8 = "Necesidad de ejercicio";
export const CHARACT1SCORE = [highscore, highscore, highscore, highscore, lowscore];
export const CHARACT2SCORE = [highscore, highscore, highscore, lowscore, lowscore];
export const CHARACT3SCORE = [highscore, highscore, lowscore, lowscore, lowscore];
export const CHARACT4SCORE = [highscore, lowscore, lowscore, lowscore, lowscore];
export const CHARACT5SCORE = [highscore, highscore, highscore, highscore, lowscore];
export const CHARACT6SCORE = [highscore, highscore, highscore, lowscore, lowscore];
export const CHARACT7SCORE = [highscore, highscore, lowscore, lowscore, lowscore];
export const CHARACT8SCORE = [highscore, lowscore, lowscore, lowscore, lowscore];
